version: '2'
services:
  mongodb:
    image: mongo:3.4
    volumes:
     - "/var/lib/mongo:/data/db"
    ports:
     - "27017:27017"
    networks:
     - tageler-network

  api:
    image: tageler/tageler-api:latest
    depends_on:
      - mongodb
    expose:
     - "3000"
    networks:
     - tageler-network
    environment:
     MONGODB_PORT_27017_TCP_ADDR: mongodb
     VIRTUAL_HOST: api.tageler.ch
     VIRTUAL_PORT: 3000

  web:
    image: tageler/tageler-frontend:latest
    depends_on:
      - api
    expose:
      - "80"
    networks:
     - tageler-network
     - traefik-web
    environment:
     VIRTUAL_HOST: www.tageler.ch
    labels:
     - "traefik.backend=web"
     - "traefik.frontend.rule=Host:www.tageler.ch"



networks:
  tageler-network:
  traefik-web:
    external:
      name: traefik_webgateway
