mongodb:
  image: mongo:latest
  volumes:
   - "/var/lib/mongodb:/var/lib/mongodb"
  ports:
   - "27017:27017"

api:
  image: tageler/tageler-api:latest
  links:
   - mongodb
  expose:
   - "3000"
  environment:
   VIRTUAL_HOST: api.tageler.ch
   VIRTUAL_PORT: 3000

web:
  image: tageler/tageler-frontend:latest
  links:
   - api:api
  environment:
   VIRTUAL_HOST: www.tageler.ch
