version: '2'
services:
  mongodb:
    image: mongo:latest
    volumes:
     - "/var/lib/mongodb:/var/lib/mongodb"
    ports:
     - "27017:27017"
    networks:
     - tageler-network

  api:
    image: tageler/tageler-api:latest
    depends_on:
      - mongodb
    expose:
     - "3000"
    networks:
     - tageler-network
    environment:
     MONGODB_PORT_27017_TCP_ADDR: mongodb
     VIRTUAL_HOST: api.tageler.ch
     VIRTUAL_PORT: 3000

  web:
    image: tageler/tageler-frontend:latest
    depends_on:
      - api
    expose:
      - "80"
    networks:
     - tageler-network
    environment:
     VIRTUAL_HOST: www.tageler.ch

networks:
  tageler-network: